### ISSUE TITLE
[LBL] problem with the creation of the LBL ref table in HARPS+ESO

### ISSUE THREAD

**Issue by eartigau** [njcuk9999/lbl#52]
When constructing the LBL ref table with HARPS-ESO data, the order numbering is offset by +1 compared to what it should be in the csv table. You get orders that go to 71 when then are 71 orders (the last one in python numbering should be 70). This causes a crash when running the code. I manually read the table, offset the order by -1 and saved the file and everything works now. This is not a problem at the compute level but at the time of ref file creation.

**Comment by njcuk9999** [comment]
An error was just passed to me that seems very related to this:
```
2024-10-25 16:32:15.733|G| We construct the spline for the "DTEMP5000" response
2024-10-25 16:32:16.673|G| We construct the spline for the "DTEMP5500" response
2024-10-25 16:32:17.487|G| We construct the spline for the "DTEMP6000" response
2024-10-25 16:32:17.487|I| *****************************************************
2024-10-25 16:32:17.488|I| Processing file 1 / 25 (24 left)
2024-10-25 16:32:17.488|I| Science file = /Users/drewweis/Documents/Research Projects/LBL-OCT-2024/lbl/dir/science/TOI667-HARPS-32-pre-offset-s2d-a_tc/r.HARPS.2023-04-04T01:24:57.140_S2D_A.fits
2024-10-25 16:32:17.613|G| SNR = 3 (SNR = 9.9269), passed SNR criteria
2024-10-25 16:32:17.655|G| The template has left/right asymmetry handled with odd/even splines
2024-10-25 16:32:17.655|G| Iteration 1
2024-10-25 16:32:17.656|G| Loaded mask table: /Users/drewweis/Documents/Research Projects/LBL-OCT-2024/lbl/dir/masks/TOI667-HARPS-32-pre-offset-s2d-a_tc_full.fits
2024-10-25 16:32:21.646|G| CCF velocity (model 1) = 34731.95 m/s
2024-10-25 16:32:21.646|G| CCF FWHM (model 1) = 2765.3 m/s
2024-10-25 16:32:21.646|G| CCF contrast = -54611.72
2024-10-25 16:32:21.647|G| CCF SNR = 80.46
2024-10-25 16:32:21.647|G| Model velocity 5.94 m/s
2024-10-25 16:32:21.647|G| Iteration 2
2024-10-25 16:32:24.985|E| Unexpected lbl_compute.py error: <class 'IndexError'>: index 71 is out of bounds for axis 0 with size 71
Traceback (most recent call last):
  File "/Users/drewweis/Documents/Research Projects/LBL-OCT-2024/lbl/lbl/recipes/lbl_compute.py", line 81, in main
    namespace = __main__(inst)
  File "/Users/drewweis/Documents/Research Projects/LBL-OCT-2024/lbl/lbl/recipes/lbl_compute.py", line 303, in __main__
    cout = general.compute_rv(inst, it, sci_data, sci_hdr,
  File "/Users/drewweis/Documents/Research Projects/LBL-OCT-2024/lbl/lbl/science/general.py", line 1507, in compute_rv
    ww_ord = wavegrid[order_num]
IndexError: index 71 is out of bounds for axis 0 with size 71

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/drewweis/Documents/Research Projects/LBL-OCT-2024/lbl/example_demo_wrap.py", line 125, in <module>
    lbl_wrap(tparams)
  File "/Users/drewweis/Documents/Research Projects/LBL-OCT-2024/lbl/lbl_wrap.py", line 217, in main
    lbl_compute.main(instrument=instrument, data_dir=data_dir,
  File "/Users/drewweis/Documents/Research Projects/LBL-OCT-2024/lbl/lbl/recipes/lbl_compute.py", line 87, in main
    raise LblException(emsg.format(**args))
lbl.core.base_classes.LblException: Unexpected lbl_compute.py error: <class 'IndexError'>: index 71 is out of bounds for axis 0 with size 71
```

**Comment by njcuk9999** [comment]
This was a bug from using old masks / old reduction - result do LBL_RESET before running!
